# Generated by Django 3.2.3 on 2021-06-04 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200118_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseaseinfo',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='rating_review',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='rating_review',
            name='patient',
        ),
        migrations.DeleteModel(
            name='consultation',
        ),
        migrations.DeleteModel(
            name='diseaseinfo',
        ),
        migrations.DeleteModel(
            name='rating_review',
        ),
    ]
